# Generated by Django 2.0.1 on 2018-01-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimesReported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence', models.CharField(default='', max_length=200)),
                ('plate_no', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('offence', models.CharField(default='', max_length=200)),
                ('plate_no', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='trafficoffence',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='trafficoffence',
            name='plate_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trafficoffence',
            name='offence',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='trafficoffence',
            name='offender',
            field=models.CharField(default='', max_length=200),
        ),
    ]
