# Generated by Django 2.0.1 on 2018-01-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0002_auto_20180125_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wanted',
            new_name='WantedList',
        ),
    ]
