# Generated by Django 2.0.1 on 2018-01-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0004_crimesreported_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimesreported',
            name='name',
        ),
    ]
