# Generated by Django 2.0.1 on 2018-01-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officerprofile',
            old_name='city',
            new_name='location',
        ),
    ]
