# Generated by Django 2.0.1 on 2018-02-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180125_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
